version: "3"

networks:
  xs2a-net:

volumes:
  xs2a-connector-data:
  xs2a-fakesmtp-data:
  xs2a-ledgers-data:
  xs2a-tpp-rest-server-data:

services:
  # Xs2a connector embedded xs2a-connector,cms,aspsp-profile
  xs2a-connector-embedded:
    image: adorsys/xs2a-connector-embedded:9.2
    container_name: xs2a-connector-embedded
    restart: on-failure
    ports:
      - "8089:8089"
      - "8189:8000"
    environment:
      - SPRING_PROFILES_ACTIVE=mock-qwac,debug_mode
      - KEYCLOAK_AUTH_SERVER_URL=http://ledgers-keycloak:8080/auth
      - XS2A_CMS_ASPSP-PROFILE_BASEURL=http://xs2a-aspsp-profile:8080/api/v1
      - XS2A_CMS_CONSENT-SERVICE_BASEURL=http://xs2a-consent-management:8080/api/v1
      - XS2A_CMS_URL=http://xs2a-consent-management:8080
      - XS2ASANDBOX_LEDGERS_URL=http://ledgers:8088
      - XS2ASANDBOX_TPPUI_ONLINE-BANKING_URL=http://xs2a-online-banking:8090/api/v1/consents/confirm/{userLogin}/{consentId}/{authorizationId}/{tan}
      - QWAC_CERTIFICATE_MOCK=${QWAC_CERTIFICATE_MOCK}
      - XS2A_FUNDS_CONFIRMATION_USER_LOGIN=admin
      - XS2A_FUNDS_CONFIRMATION_USER_PASSWORD=admin123
      - XS2A_BANK_PROFILE_PATH=/opt/profile/bank_profile_ledgers.yml
      - SPRING_DATASOURCE_URL=jdbc:postgresql://xs2a-consent-management-db/consent?currentSchema=consent
      - SPRING_DATASOURCE_USERNAME=cms
      - SPRING_DATASOURCE_PASSWORD=cms
      - SERVER_KEY=secret123
      - SPRING_LIQUIBASE_ENABLED=true
      - USED-NON-RECURRING-CONSENT-EXPIRATION.CRON.EXPRESSION=0 0 * * * *
    volumes:
      - ./bank-profile/bank_profile_ledgers.yml:/opt/profile/bank_profile_ledgers.yml
    networks:
      - xs2a-net
    depends_on:
      - ledgers
      - xs2a-consent-management-db

  # Xs2a consent management DB
  xs2a-consent-management-db:
    image: centos/postgresql-95-centos7
    container_name: xs2a-consent-management-db
    restart: on-failure
    volumes:
      - xs2a-connector-data:/var/lib/pgsql/data
      - ./db-scripts/pg-create-schema.sh:/usr/share/container-scripts/postgresql/start/zzz-create-schema.sh
    expose:
      - 5432
    ports:
      - "5432:5432"
    networks:
      - xs2a-net
    environment:
      - POSTGRESQL_ADMIN_PASSWORD=postgres
      - POSTGRESQL_DATABASE=consent
      - POSTGRESQL_USER=cms
      - POSTGRESQL_PASSWORD=cms

  # Xs2a online banking backend
  xs2a-online-banking:
    image: adorsys/xs2a-online-banking
    container_name: xs2a-online-banking
    restart: on-failure
    build:
      context: online-banking/online-banking-app
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
      - "8190:8000"
    depends_on:
      - ledgers
      - xs2a-connector-embedded
      - xs2a-consent-management-db
    networks:
      - xs2a-net
    environment:
      KEYCLOAK_AUTH_SERVER_URL: "http://ledgers-keycloak:8080/auth"
      XS2A_URL: "http://xs2a-connector-embedded:8089"
      LEDGERS_URL: "http://ledgers:8088"
      CMS_URL: "http://xs2a-connector-embedded:8089"
      OBA_URL: "http://localhost:4400"
      SELF_URL: "http://localhost:8090"
      ONLINE_BANKING_SCA_LOGINPAGE: "http://localhost:4400/"
      ONLINE_BANKING_SCA_UIREDIRECT: "true"
      ONLINE-BANKING_URL: "http://xs2a-online-banking:8090/api/v1/consents/confirm/{userLogin}/{consentId}/{authorizationId}/{tan}"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://xs2a-consent-management-db/consent?currentSchema=consent"
      SPRING_DATASOURCE_USERNAME: "cms"
      SPRING_DATASOURCE_PASSWORD: "cms"
      SERVER_KEY: "secret123"

  # Ledgers
  ledgers:
    image: adorsys/ledgers:4.1
    container_name: ledgers
    restart: on-failure
    networks:
      - xs2a-net
    ports:
      - "8088:8088"
      - "8188:8001"
    environment:
      - SPRING_PROFILES_ACTIVE=postgres,develop
      - SPRING_JPA_SHOW_SQL=false
      - KEYCLOAK_AUTH_SERVER_URL=http://ledgers-keycloak:8080/auth
      - DB_HOST=xs2a-consent-management-db
      - DB_URL=jdbc:postgresql://xs2a-consent-management-db/consent?currentSchema=ledgers
      - DB_DATABASE=consent
      - DB_USER=cms
      - DB_PASSWORD=cms
      - LIQUIBASE_ENABLED=true
      - LEDGERS_SCA_MULTILEVEL_ENABLED=false
      - LEDGERS_SCA_AUTHORISATION_CONFIRMATION_ENABLED=false
      - SPRING_MAIL_HOST=fakesmtp
      - SPRING_MAIL_PORT=25
      - LEDGERS_SCA_AUTHCODE_APP_OTP_SOCKET_SERVICE_URL=http://xs2a-online-banking:8090/api/v1/decoupled/message
    volumes:
      - xs2a-ledgers-data:/var/lib/data
    depends_on:
      - fakesmtp
      - ledgers-keycloak

  # Keycloak as IDP
  ledgers-keycloak:
    image: adorsys/ledgers-keycloak:${LEDGERS_VERSION}
    container_name: ledgers-keycloak
    restart: on-failure
    networks:
      - xs2a-net
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin

  # Xs2a online banking frontend
  xs2a-online-banking-ui:
    image: adorsys/xs2a-online-banking-ui
    restart: on-failure
    build:
      context: oba-ui
      dockerfile: Dockerfile
    ports:
      - "4400:4400"
    networks:
      - xs2a-net
    environment:
      ONLINE_BANKING_SERVER_URL: "http://xs2a-online-banking:8090"
      DEV_PORTAL_URL_EXT: "http://localhost:4206"
    depends_on:
      - xs2a-online-banking
      - developer-portal-ui

  # TPP-UI
  xs2a-tpp-ui:
    image: adorsys/xs2a-bank-tpp-ui
    restart: on-failure
    environment:
      - TPP_REST_SERVER_URL=http://xs2a-tpp-rest-server:8093
      - CERT_GEN_URL=http://certificate-generator:8092
      - CERT_GEN_ENABLED=true
    build:
      context: tpp-ui
      dockerfile: Dockerfile
    ports:
      - "4205:4205"
    networks:
      - xs2a-net
    depends_on:
      - certificate-generator
      - xs2a-tpp-rest-server

  # TPP-REST-SERVER
  xs2a-tpp-rest-server:
    image: adorsys/xs2a-tpp-rest-server
    restart: on-failure
    environment:
      KEYCLOAK_AUTH_SERVER_URL: "http://ledgers-keycloak:8080/auth"
      LEDGERS_URL: "http://ledgers:8088"
      SPRING_DATASOURCE_HIKARI_JDBCURL: "jdbc:postgresql://xs2a-consent-management-db/consent?currentSchema=consent"
      SPRING_DATASOURCE_HIKARI_USERNAME: "cms"
      SPRING_DATASOURCE_HIKARI_PASSWORD: "cms"
      SPRING_CONSENT_DATASOURCE_HIKARI_JDBCURL: "jdbc:postgresql://xs2a-consent-management-db/consent?currentSchema=consent"
      SPRING_CONSENT_DATASOURCE_HIKARI_USERNAME: "cms"
      SPRING_CONSENT_DATASOURCE_HIKARI_PASSWORD: "cms"
      SPRING_TPP_DATASOURCE_HIKARI_JDBCURL: "jdbc:postgresql://xs2a-consent-management-db/consent?currentSchema=tpp"
      SPRING_TPP_DATASOURCE_HIKARI_USERNAME: "cms"
      SPRING_TPP_DATASOURCE_HIKARI_PASSWORD: "cms"
    build:
      context: tpp-app/tpp-rest-server
      dockerfile: Dockerfile
    ports:
      - "8093:8093"
      - "5005:5005"
    networks:
      - xs2a-net
    depends_on:
      - ledgers
      - xs2a-consent-management-db
    volumes:
      - xs2a-tpp-rest-server-data:/var/lib/data

  # Developer portal ui
  developer-portal-ui:
    image: adorsys/xs2a-bank-devportal
    restart: on-failure
    build:
      context: developer-portal-ui
      dockerfile: Dockerfile
    ports:
      - "4206:4206"
    networks:
      - xs2a-net
    depends_on:
      - xs2a-connector-embedded
    environment:
      - XS2A_URL=http://xs2a-connector-embedded:8089
      - ASPSP_URL=http://xs2a-connector-embedded:8089

  # Certificate generator
  certificate-generator:
    image: adorsys/xs2a-certificate-generator
    restart: on-failure
    build:
      context: certificate-generator
      dockerfile: Dockerfile
    ports:
      - "8092:8092"
    networks:
      - xs2a-net

  # Fake SMTP
  fakesmtp:
    image: munkyboy/fakesmtp:latest
    networks:
      - xs2a-net
    volumes:
      - xs2a-fakesmtp-data:/var/mail
